/*=====================================================================*/
/*                                                                     */
/* PROGRAMMA NAAM:      Constant                (Constant.h)           */
/* AUTEUR:              Resourser                                      */
/* BESCHRIJVING:                                                       */
/*   In deze H-file staan alle constanten die het programma            */
/*   gebruikt.                                                         */
/*                                                                     */
/*                                                                     */
/*                                                                     */
/* DATUM:                  3 oktober 1996                              */
/*=====================================================================*/

#define	       PI                3.1416
#define	       P2I               6.2832

#define	       graphkeuze        0
#define	       analysekeuze      1
#define	       rotatekeuze       2
#define	       verplaatskeuze    3
#define	       zoomkeuze         4
#define	       zfactorkeuze      5
#define	       configkeuze       6
#define	       quitkeuze        -1

#define	       defaultXmin      -4
#define	       defaultXmax       4
#define	       defaultYmin      -4
#define	       defaultYmax       4
#define	       defaultXsamples  36
#define	       defaultzfactor    1
#define	       defaultPhiX       0.25*PI
#define	       defaultPhiZ       1.25*PI

#define	       arraysize        70
#define	       Xsamplesmax      arraysize
#define	       Xsamplesmin      16

#define	       zfactormin        0.1
#define	       zfactormax    10000

#define	       Cmaxmax        400
#define	       Cminmin       -400
#define	       deltaCmin        0.04

/* kleurnamen */

#define	       zwart            0
#define	       blauw            1
#define	       lichtblauw       2
#define	       cyan             3
#define	       lichtcyan        4
#define	       groen            5
#define	       lichtgroen       6
#define	       lichtgrijs       7
#define	       donkergrijs      8
#define	       geel             9
#define	       bruin           10
#define	       rood            11
#define	       lichtrood       12
#define	       lichtmagenta    13
#define	       magenta         14
#define	       wit             15

/* ascii tekens */

#define	       Return          13
#define	       Backspace        8
#define	       Spatie          32
#define	       asciiblokteken 219
#define	       karakterbreedte  8