/*=====================================================================*/
/*                                                                     */
/* PROGRAMMA NAAM:      Array.h           (Array.h)                    */
/* AUTEUR:              Resourser                                      */
/* BESCHRIJVING:                                                       */
/*   In deze H-file staan de verwijzing naar de module die het         */
/*   functieonderzoek voor zijn rekening neemt                         */
/*                                                                     */
/*                                                                     */
/*                                                                     */
/* DATUM:                  3 oktober 1996                              */
/*=====================================================================*/


extern float Functie(point);

