/*=====================================================================*/
/*                                                                     */
/* PROGRAMMA NAAM:      Headerfile van Coorsys (Coorsys.h)             */
/* AUTEUR:              Resourser                                      */
/* BESCHRIJVING:                                                       */
/*    In deze file staan de variabelen die nodig zijn voor het         */
/*    berekenen van de coordinatensystem bovenin het scherm            */
/*                                                                     */
/*    Het system is een klein 3-dimentionaal object die met de         */
/*    presentatie meeroteert. De coordinaten die hieronder             */
/*    gedeclareerd zijn hebben te maken met de grootte van het object  */
/*    alsmede de kleuren van het object                                */
/*                                                                     */
/* DATUM:                  3 oktober 1996                              */
/*=====================================================================*/

#define		Xlijn		33
#define		Ylijn		33
#define		Zlijn		33

#define		Xkleur	rood
#define		Ykleur	lichtgroen
#define		Zkleur	lichtblauw